### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by WDWLWY** [Desny/traffic_light_rl#1]
这个main.py是用来训练的吗？？那训练好的模型怎么测试？
### ****

**Comment by Desny** [comment]
main.py可以进行训练或测试，根据你命令行传入的参数不同切换不同的模式。如果你想测试训练好的模型，那么需要你在命令行传入参数或直接修改main.py上方的flags默认参数值：mode='eval'和network_file='xx.pth'（建议写权重文件的全路径）

**Comment by way-thu** [comment]
@WDWLWY 您好，请问您还在使用这个代码吗？可以的话能否交流一下，我有许多地方没太明白，十分感谢！

**Comment by Desny** [comment]
> @WDWLWY 您好，请问您还在使用这个代码吗？可以的话能否交流一下，我有许多地方没太明白，十分感谢！

目前不再使用这个代码，但是如果你有问题可以在b站私信我，我的b站账号是“二营长向强化学习开炮”。
