### ISSUE TITLE
help

### ISSUE THREAD

**Issue by way-thu** [Desny/traffic_light_rl#2]
您好，请问您的状态、动作和奖励具体是怎么定义的啊，我看代码的时候没太能理解，所以来请教您，希望您能解答，十分感谢！

**Comment by way-thu** [comment]
以及有使用到target network嘛？我看main.py中有定义一个target，没太能理解是不是target network的意思
![image](https://github.com/Desny/traffic_light_rl/assets/113359869/d1796b29-af26-4859-aa28-0815b6e30712)

**Comment by Desny** [comment]
> 您好，请问您的状态、动作和奖励具体是怎么定义的啊，我看代码的时候没太能理解，所以来请教您，希望您能解答，十分感谢！

状态：道路密度（道路目前的车辆数/道路上满车辆数），动作（信号灯相位），奖励（我用的奖励函数比较简单，就是判断我选择的信号灯相位是否疏通了等待时间最长的道路，是->+1，否->-1）

**Comment by Desny** [comment]
> 以及有使用到target network嘛？我看main.py中有定义一个target，没太能理解是不是target network的意思 ![image](https://user-images.githubusercontent.com/113359869/282220977-d1796b29-af26-4859-aa28-0815b6e30712.png)

是target_network，也用到了target_network
